feat(compiler): suggest better suggestions for imports on unknown variable
This improves the overall compiler unknown variables suggestions by listing
all imported modules values in the scope so it can now recommends imports.

For example with the following code (described in GitHub issue #2697):
```
import gleam/io

pub fn main() {
  let numbers = [1, 2, 3, 4, 5]
  debug(numbers) // Intended to use io.debug but mistakenly omitted 'io.'
}
```

The current version of the compiler provides the following error:
```
error: Unknown variable
  ┌─ /path/to/project/src/my_project.gleam:5:3
  │
5 │   debug(numbers)
  │   ^^^^^ Did you mean `True`?
```

With my changes the suggestions are a bit smarter:
```
error: Unknown variable
  ┌─ /Users/shellbear/code/gleamio/src/gleamio.gleam:5:3
  │
5 │   debug(numbers) // Intended to use io.debug but mistakenly omitted 'io.'
  │   ^^^^^ Did you mean `io.debug`?

The name `debug` is not in scope here.
```